import { Sparkles, ChevronDown } from 'lucide-react'
import { useState } from 'react'

export function AIBadge({ isLive }) {
  return (
    <div
      className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-medium ${isLive
        ? 'border-teal-400/30 bg-teal-400/10 text-teal-300'
        : 'border-amber-400/30 bg-amber-400/10 text-amber-300'
        }`}
    >
      <Sparkles className="h-3.5 w-3.5" />
      {isLive ? 'Generated by Gemini AI' : 'Sample data — Gemini AI offline'}
    </div>
  )
}

export function PromptReveal({ prompt }) {
  const [open, setOpen] = useState(false)
  if (!prompt) return null

  return (
    <div className="mt-4 border-t border-white/5 pt-3">
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-1.5 text-xs font-medium text-white/40 transition-colors hover:text-white/70"
      >
        <ChevronDown className={`h-3.5 w-3.5 transition-transform ${open ? 'rotate-180' : ''}`} />
        View Prompt Used
      </button>
      {open && (
        <pre className="mt-2 max-h-48 overflow-auto rounded-lg bg-black/30 p-3 text-[11px] leading-relaxed text-white/50 font-mono whitespace-pre-wrap">
          {prompt}
        </pre>
      )}
    </div>
  )
}
