/**
 * services/pdfService.js
 * Generates a PDF complaint letter using PDFKit.
 * Returns the PDF as a Base64-encoded string so it can be sent over JSON.
 */

const PDFDocument = require('pdfkit')

/**
 * Builds a PDF from a complaint letter text.
 * @param {string} letterText - The full complaint letter text
 * @param {string} trackingId - Used in the footer
 * @returns {Promise<Buffer>} PDF buffer
 */
function buildComplaintPDF(letterText, trackingId) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 60, size: 'A4' })
    const chunks = []

    doc.on('data', (chunk) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    // ── Header ───────────────────────────────────────────────────────────────
    doc
      .fontSize(18)
      .fillColor('#1a1a2e')
      .font('Helvetica-Bold')
      .text('BharatSetu AI', { align: 'center' })

    doc
      .fontSize(9)
      .fillColor('#666')
      .font('Helvetica')
      .text('AI-Powered Civic Complaint Letter', { align: 'center' })

    doc.moveDown(0.5)

    // Divider
    doc
      .moveTo(60, doc.y)
      .lineTo(doc.page.width - 60, doc.y)
      .strokeColor('#cccccc')
      .stroke()

    doc.moveDown(1)

    // ── Letter body ──────────────────────────────────────────────────────────
    doc
      .fontSize(11)
      .fillColor('#111')
      .font('Helvetica')
      .text(letterText, { lineGap: 4 })

    doc.moveDown(2)

    // ── Footer ───────────────────────────────────────────────────────────────
    doc
      .moveTo(60, doc.y)
      .lineTo(doc.page.width - 60, doc.y)
      .strokeColor('#cccccc')
      .stroke()

    doc.moveDown(0.5)

    doc
      .fontSize(8)
      .fillColor('#999')
      .text(
        `Generated by BharatSetu AI | Tracking ID: ${trackingId} | ${new Date().toLocaleDateString('en-IN')}`,
        { align: 'center' }
      )

    doc.end()
  })
}

/**
 * Generates a complaint PDF and returns it as a Base64 string.
 * @param {string} letterText
 * @param {string} trackingId
 * @returns {Promise<string>} Base64-encoded PDF
 */
async function generateComplaintPDFBase64(letterText, trackingId) {
  const buffer = await buildComplaintPDF(letterText, trackingId)
  return buffer.toString('base64')
}

module.exports = { generateComplaintPDFBase64 }
